language: node_js
node_js:
  - "10"
  - "8"
notifications:
  recipients:
    - piro.outsider.reflex@gmail.com
before_script:
  - cd webextensions
  - npm install
  - make update_extlib
  - make install_extlib
script:
  - make lint
before_deploy:
  - make
deploy:
  provider: releases
  api_key:
    secure: "LSjWBryEXJwjhMAZ3Hs3w1wbN6Gz1ZfO3sx8E/QhLVjCe1JQqNqt2FwHc3uKdcwyicGONFESxHAC3/ak6pCT/SyINhCWptcgLMc/USbsYzu9OleWfpjeAuHbK331azxrwyk705+RFqJ/P/IfWeTkeknM2L1cERSJfrCnyA5LQ64="
  file:
    - textlink-we.xpi
  skip_cleanup: true
  on:
    repo: piroor/textlink
    tags: true
